name: Build Android APK
run-name: ${{ github.event.inputs.repository }}:${{ github.event.inputs.taskName }}

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Git repository URL"
        required: true
        default: "https://github.com/android/sunflower"
      jdkVersion:
        description: "OpenJDK version to use: 8 / 11 / 17 etc."
        required: false
        default: "21"
      taskName:
        description: "build.gradle task name: assemble[Flavor]Debug"
        required: false
        default: "assembleDebug"

jobs:
  build:
    runs-on: ubuntu-latest # Android SDK is built-in in this image
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ github.event.inputs.jdkVersion }}

      - name: Clone project
        run: git clone --recurse-submodules --depth=1 ${{ github.event.inputs.repository }} workspace

      - name: Build APK
        working-directory: ./workspace
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew ${{ github.event.inputs.taskName }} --stacktrace
          
      - name: Upload Gradle Problems Report (if exists)
        if: always()
        run: |
          if [ -f "workspace/.build/reports/problems/problems-report.html" ]; then
            echo "Found problems-report.html, uploading..."
            mkdir -p temp-report
            cp workspace/.build/reports/problems/problems-report.html temp-report/
          else
            echo "No problems-report.html found, skipping upload."
          fi
        shell: bash

      - name: Upload problems-report.html artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: problems-report
          path: temp-report/
          retention-days: 1

      - name: Upload the APK artifact with 1 day retention
        uses: actions/upload-artifact@v4
        with:
          path: ./**/*.apk
          name: apk-archive
          retention-days: 1
